spring:
   application:
     name:user-manage-sys
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/user-manage-db
     username: root
     password: Google!123

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: hokumei.sys.usermanagesys.model
  generator:
    fileOverride: true
  configuration:
    # 开启下划线转驼峰命名
    map-underscore-to-camel-case: true
    local-cache-scope: statement

  global-config:
    db-config:
      logic-delete-field: flag             # ???????????
      logic-delete-value: 1               # ??????????? 1?
      logic-not-delete-value: 0


server:
  servlet:
    context-path: /api






